[services.api]
baseDirectory = "packages/api"
language = "javascript"
packageManager = "pnpm"
nodeVersion = "22"
installCommand = "NODE_ENV=development pnpm install --frozen-lockfile"
buildCommand = "pnpm --filter @resendbyte/api... build"
startCommand = "node dist/server.js"
port = 3000

[services.web]
baseDirectory = "apps/web"
language = "javascript"
framework = "nextjs"
packageManager = "pnpm"
nodeVersion = "22"
installCommand = "NODE_ENV=development pnpm install --frozen-lockfile"
buildCommand = "pnpm --filter @resendbyte/web... build"
startCommand = "next start"
port = 3000
