apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resendbyte-api
  namespace: resendbyte
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resendbyte-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resendbyte-sidekiq
  namespace: resendbyte
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resendbyte-sidekiq
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
